### ISSUE TITLE
team planning - written description

### ISSUE THREAD

**Issue by jamesisaacs2** [cryptoWinterGuys/crypton-old#10]
- purpose of app
- how app will work
- etc

**Comment by jamesisaacs2** [comment]
test comment

**Comment by jamesisaacs2** [comment]
project write up complete (The Conversation).

**Comment by kevinsanroman84** [comment]
[https://star-order-90d.notion.site/Crypton-from-cryptoWinterGuys-c6b7aeeb3cb94318a3ea0fd333d00e24](url)

**Comment by damon-m-deng** [comment]
User Story:
	- App page
		-- Provides users the most updated crypto information (ranking, price...)
		-- Displays best/worst performers
	- Landing page:
		-- Users have options to sign up/sign in
		-- User can learn more about us (About us/contact info...)

User flow:
- Landing page: welcomes the user, gives user the option to sign-in / sign-up / About us
- Main/Utility/App page:
	-- Table: review the most updated crypto prices

Supporting techniques
- HTML, CSS
	- For both landing page and app page
	- BootStrap: functional addons such as navBars, cards, etc
- JS:
	- API(fetch/.then/.catch methods): connecting to the API endpoint to fetch data, then insert the data to the Table of the App page
	- Logical flow control: if/else, iterations, error handling
